"use client"
import { ThemeProvider } from "@mui/system";
import theme from "@/lib/default-theme";

import SortBlock1 from "@/components/slide-parts/sort-block1";

import SlidePage from "@/components/slide-parts/slide-page";

import Link from "next/link";

export default function Home() {

  const animeSequence = [
    //テキストがないと最初の移動が適用されない
    // {"action": "break", "desc": "text"},
    {"action": "break", "desc": "このページではボゾソートについて説明します"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e4", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e4"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e7"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e7", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e3", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e2", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e5"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e3"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e6"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e6", "sel2": ".e2"},
    {"action": "swap", "sel1": ".e5", "sel2": ".e1"},
    {"action": "swap", "sel1": ".e1", "sel2": ".e4"},
    {"action": "break", "desc": "ボゾソートはソートができるまで、ランダムに要素を入れ替えるアルゴリズムです\nランダムに要素を入れ替えて続ければいつかは正しく並ぶ可能性があるだろうというアイディアに基づいています\nこのようなアイディアは無限の猿定理として知られています"},
    {"action": "break", "desc": "200回試行しましたが、ソートできませんでした。"},
  ];
  
  return (
    <ThemeProvider theme={theme}>
      <SlidePage title="ボゾソート" animeSequence={animeSequence}>
        <div className="flex h-full w-full sort-elements content-center">
          <SortBlock1 percent={30} className="e1"/>
          <SortBlock1 percent={20} className="e2"/>
          <SortBlock1 percent={90} className="e3"/>
          <SortBlock1 percent={10} className="e4"/>
          <SortBlock1 percent={25} className="e5"/>
          <SortBlock1 percent={15} className="e6"/>
          <SortBlock1 percent={50} className="e7"/>
        </div>
      </SlidePage>
    </ThemeProvider>
  );
}
